### ISSUE TITLE
KeyError: -7

### ISSUE THREAD

**Issue by ulipoto** [bicarlsen/easy-biologic#18]
I used `python -m easy_biologic.find_devices` in the terminal to find my potentiostat and got "VMP3: USB0" as a result. Using that for `bl = ebl.BiologicDevice('VMP3: USB0')` does not work. Using only "USB0" returns `KeyError: -7`. And apparently, error -7 does not exist in the error list.

The Biologic USB driver is installed and the EC-lab software works fine with USB connection. I'm using the Biologic VMP3B-10 potentiostat.

Do I maybe use the wrong keyword with 'USB0'?

Code:
```
import easy_biologic as ebl
import easy_biologic.base_programs as blp

bl = ebl.BiologicDevice('USB0')
```

Full error:
````
File "C:\ProgramData\Anaconda3\lib\site-packages\easy_biologic\lib\ec_errors.py", line 108, in __init__
    ( code, message ) = EcError.errors[ value ]

KeyError: -7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\Python\untitled0.py", line 12, in <module>
    bl = ebl.BiologicDevice('USB0')

  File "C:\ProgramData\Anaconda3\lib\site-packages\easy_biologic\device.py", line 61, in __init__
    self.populate_info()

  File "C:\ProgramData\Anaconda3\lib\site-packages\easy_biologic\device.py", line 209, in populate_info
    self.connect()

  File "C:\ProgramData\Anaconda3\lib\site-packages\easy_biologic\device.py", line 178, in connect
    ecl.init_channels(

  File "C:\ProgramData\Anaconda3\lib\site-packages\easy_biologic\lib\ec_lib.py", line 864, in init_channels
    validate( err )

  File "C:\ProgramData\Anaconda3\lib\site-packages\easy_biologic\lib\ec_lib.py", line 1615, in validate
    raise EcError( err )

  File "C:\ProgramData\Anaconda3\lib\site-packages\easy_biologic\lib\ec_errors.py", line 111, in __init__
    raise ValueError( f'Unknown error value {value}.' )

ValueError: Unknown error value -7.`
```

**Comment by bicarlsen** [comment]
It seems this error is coming from [`easy_biologic.lib.ec_lib#init_channels`](https://github.com/bicarlsen/easy-biologic/blob/08459a66da5f52fe85b2e3245cecc3ae5d49f1fc/easy_biologic/lib/ec_lib.py#L853) where `BL_LoadFirmware` is called.

From the User's manual (EC-Lab Development Package: Users Guide, Version 6.00 - April 2017) The error is `(ERR_GEN_NOCHANNEL[S]ELECTED, no channel selected)`.

Back tracking a bit, it appears that the issue is coming from [`easy_biologic.device.BiologicDevice#connect`](https://github.com/bicarlsen/easy-biologic/blob/08459a66da5f52fe85b2e3245cecc3ae5d49f1fc/easy_biologic/device.py#L175) where `self.info.NumberOfChannels` is being used as to determine the channels to initialize. This info is coming from the call to [`easy_biologic.lib.ec_lib#connect`](https://github.com/bicarlsen/easy-biologic/blob/08459a66da5f52fe85b2e3245cecc3ae5d49f1fc/easy_biologic/device.py#L169) to get information about the channels, My best guess is that this is where something is going wrong.

Unfortuantely, I don't have access to a `VMP3B-10` and can not recreate the error on my devices so you may have to do some playing around. I suggest printing out `BiologicDevice.info` before the call to `ec_lib#init_channels` to verify the channels are correct, and if not, try to traceback from there where the issue is being caused.
