### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'

### ISSUE THREAD

**Issue by Rib20045** [bicarlsen/easy-biologic#32]
```
Traceback (most recent call last):
  File "c:\Users\rahma\Downloads\Python\Keithley stuff\Main.py", line 1, in <module>
    import easy_biologic as ebl
  File "C:\Users\rahma\Downloads\Python\Keithley stuff\venv\Lib\site-packages\easy_biologic\__init__.py", line 8, in <module>
    from .device import BiologicDevice
  File "C:\Users\rahma\Downloads\Python\Keithley stuff\venv\Lib\site-packages\easy_biologic\device.py", line 12, in <module>
    from .lib.ec_errors import EcError
  File "C:\Users\rahma\Downloads\Python\Keithley stuff\venv\Lib\site-packages\easy_biologic\lib\__init__.py", line 1, in <module>
    from . import data_parser
  File "C:\Users\rahma\Downloads\Python\Keithley stuff\venv\Lib\site-packages\easy_biologic\lib\data_parser.py", line 30, in <module>
    from . import ec_lib as ecl
  File "C:\Users\rahma\Downloads\Python\Keithley stuff\venv\Lib\site-packages\easy_biologic\lib\ec_lib.py", line 565, in <module>
    globals()[ async_name ] = asyncio.coroutine( method )
                              ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

```

All I did was import the module

```
import easy_biologic as ebl
import easy_biologic.base_programs as blp
import pymeasure as pym
from pymeasure.adapters import VISAAdapter
from pymeasure.instruments.keithley import Keithley2750
```

**Comment by bicarlsen** [comment]
This is probably caused by a version bump (see also Issue #27 and the associated PR). Which version of Python are you using?
